<a href="https://colab.research.google.com/github/falahamro/Predictive-/blob/main/K_Fold_Cross_Validation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as no
from sklearn.datasets import load_iris

In [44]:
iris = load_iris()

train test split

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target, test_size=0.3)

In [46]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

0.9555555555555556

In [47]:
svm = SVC(gamma ='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

1.0

In [48]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

We create a K Fold Model to avoid fitting 

In [50]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [67]:
for train_index, test_index in kf.split([11, 12, 13, 14, 15, 16, 17, 18, 19]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [68]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [69]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [70]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [71]:
for train_index, test_index in folds.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index],iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


In [72]:
scores_logistic

[0.96, 0.96, 0.94]

In [73]:
scores_svm

[0.98, 0.98, 0.96]

In [74]:
scores_rf

[0.98, 0.94, 0.98]

In [75]:
from sklearn.model_selection import cross_val_score

In [77]:
score_lr=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

In [78]:
score_lr

array([0.96, 0.96, 0.94])

In [79]:
scores_rf=cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

In [80]:
scores_rf

array([0.98, 0.98, 0.96])

In [81]:
no.average(scores_rf)

0.9733333333333333